name: Atualiza README com stats privados

on:
  workflow_dispatch:  # executa manualmente
  schedule:
    - cron: '0 1 * * *' # executa todo dia às 01h
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera seção de stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=gabriellprado&show_icons=true&theme=react&include_all_commits=true&count_private=true&token=${GH_TOKEN})" > stats.md

      - name: Atualiza README final
        run: |
          sed '/<!--STATS_SECTION-->/r stats.md' README.template.md > README.md

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualiza README com stats privados"
          git push
        continue-on-error: true
